apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-challenge
spec:
  replicas: 3
  selector:
    matchLabels:
      app: challenge
template:
  metadata:
    labels:
      app: challenge
  spec:
    containers:
      - name: appserver
        ports:
        - containerPort:3000
      - name: postgres
        image: postgres:10.1
        imagePullPolicy: "IfNotPresent"
        ports:
          - containerPort: 5432
        envFrom:
          - configMapRef:
              name: postgres-config
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: postgredb
    volumes:
      - name: postgredb
        persistentVolumeClaim:
          claimName: postgres-pv-claim